// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package datepicker

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"crypto/rand"
	"fmt"
	"github.com/coreycole/datastarui/components/calendar"
	"github.com/coreycole/datastarui/components/dateinput"
	"github.com/coreycole/datastarui/utils"
	"strings"
	"time"
)

// datePickerSignals defines the reactive state for the DatePicker component
type DatePickerSignals struct {
	// Open state of the popover
	Open bool `json:"open"`

	// Input value (what user sees in the input field - YYYY/MM/DD format)
	InputValue string `json:"inputValue"`

	// Selected date in internal format (YYYY-MM-DD)
	SelectedDate string `json:"selectedDate"`

	// Range start date (YYYY-MM-DD format)
	RangeStart string `json:"rangeStart"`

	// Range end date (YYYY-MM-DD format)
	RangeEnd string `json:"rangeEnd"`

	// Current display month (YYYY-MM-DD format, first day of month)
	DisplayMonth string `json:"displayMonth"`

	// Validation state
	IsValid bool `json:"isValid"`

	// Error message for invalid dates
	ErrorMessage string `json:"errorMessage"`

	// Whether user is currently typing (affects calendar sync behavior)
	IsTyping bool `json:"isTyping"`

	// Focused date in calendar (for keyboard navigation)
	FocusedDate string `json:"focusedDate"`

	// Highlighted date (for keyboard navigation within calendar)
	HighlightedDate string `json:"highlightedDate"`

	// Calendar-specific signals (needed for Calendar component compatibility)
	CurrentDate string `json:"currentDate"`
	Mode        string `json:"mode"`
	Today       string `json:"today"`

	// DateInput-specific signals (needed for DateInput component compatibility)
	DateValue       string `json:"dateValue"`
	StartInputValue string `json:"startInputValue"`
	StartDateValue  string `json:"startDateValue"`
	EndInputValue   string `json:"endInputValue"`
	EndDateValue    string `json:"endDateValue"`
	EndDateEnabled  bool   `json:"endDateEnabled"`
}

// calendarIconButton creates a calendar icon button component for use as postfix
func calendarIconButton(onClickHandler string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button type=\"button\" class=\"text-muted-foreground hover:text-foreground\" tabindex=\"-1\" data-on-click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(onClickHandler)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 68, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><svg class=\"h-4 w-4\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 2v4\"></path> <path d=\"M16 2v4\"></path> <rect width=\"18\" height=\"18\" x=\"3\" y=\"4\" rx=\"2\"></rect> <path d=\"M3 10h18\"></path></svg></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DatePicker renders a date picker with input field and calendar popover
func DatePicker(args DatePickerProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// Generate unique ID if not provided
		datePickerID := args.ID
		if datePickerID == "" {
			b := make([]byte, 4)
			rand.Read(b)
			datePickerID = fmt.Sprintf("datepicker_%x", b)
		}

		// CloseOnSelect defaults based on mode
		closeOnSelect := true
		if args.Mode == "range" {
			closeOnSelect = false // Don't close on first selection in range mode
		}

		// Determine initial values
		initialInputValue := ""
		initialSelectedDate := args.SelectedDate
		initialRangeStart := args.RangeStart
		initialRangeEnd := args.RangeEnd

		// Set initial display month
		initialDisplayMonth := args.DefaultDate
		if initialDisplayMonth == "" {
			if args.SelectedDate != "" {
				initialDisplayMonth = args.SelectedDate[:7] + "-01" // First day of selected month
			} else if args.RangeStart != "" {
				initialDisplayMonth = args.RangeStart[:7] + "-01"
			} else {
				// Current month
				now := time.Now()
				initialDisplayMonth = fmt.Sprintf("%04d-%02d-01", now.Year(), now.Month())
			}
		}

		// Convert internal date to display format for input
		if args.Mode == "range" {
			if initialRangeStart != "" && initialRangeEnd != "" {
				startDisplay := strings.ReplaceAll(initialRangeStart, "-", "/")
				endDisplay := strings.ReplaceAll(initialRangeEnd, "-", "/")
				initialInputValue = startDisplay + " - " + endDisplay
			} else if initialRangeStart != "" {
				initialInputValue = strings.ReplaceAll(initialRangeStart, "-", "/")
			}
		} else {
			if initialSelectedDate != "" {
				// Convert YYYY-MM-DD to MM/DD/YYYY
				parts := strings.Split(initialSelectedDate, "-")
				if len(parts) == 3 {
					initialInputValue = parts[1] + "/" + parts[2] + "/" + parts[0]
				}
			}
		}

		// Set appropriate placeholder based on mode
		placeholder := args.Placeholder
		if placeholder == "" {
			if args.Mode == "range" {
				placeholder = "MM/DD/YYYY - MM/DD/YYYY"
			} else {
				placeholder = "MM/DD/YYYY"
			}
		}

		// Create signals for reactive state (unified for all components)
		now := time.Now()
		todayStr := now.Format("2006-01-02")

		signals := utils.Signals(datePickerID, DatePickerSignals{
			Open:            false,
			InputValue:      initialInputValue,
			SelectedDate:    initialSelectedDate,
			RangeStart:      initialRangeStart,
			RangeEnd:        initialRangeEnd,
			DisplayMonth:    initialDisplayMonth,
			IsValid:         true,
			ErrorMessage:    "",
			IsTyping:        false,
			FocusedDate:     "",
			HighlightedDate: "",

			// Calendar-specific signals
			CurrentDate: initialDisplayMonth,
			Mode:        args.Mode,
			Today:       todayStr,

			// DateInput-specific signals
			DateValue:       initialSelectedDate,
			StartInputValue: "",
			StartDateValue:  initialRangeStart,
			EndInputValue:   "",
			EndDateValue:    initialRangeEnd,
			EndDateEnabled:  args.Mode == "range",
		})

		// Container classes
		containerClasses := "relative " + args.Class

		// Use expression builders for clean event handling
		popoverHandler := newDatePickerPopoverHandler(datePickerID, datePickerID, args.Mode, signals)
		clickOutsideHandler := popoverHandler.buildClickOutsideHandler()
		calendarIconClickHandler := popoverHandler.buildOpenTriggerHandler()

		// DateInput ID - use SAME ID for shared signal namespace
		dateInputID := datePickerID
		var templ_7745c5c3_Var4 = []any{containerClasses}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div data-slot=\"datepicker\" data-datepicker-id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(datePickerID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 200, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(signals.DataSignals)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 201, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" data-on-click__outside=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(clickOutsideHandler)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 202, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var4).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, args.Attributes)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "><!-- Hidden input for form submission -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if args.Name != "" {
			if args.Mode == "range" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<!-- Range mode: separate inputs for start and end --> <input type=\"hidden\" name=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var9 string
				templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(args.Name + "_start")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 212, Col: 32}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" data-bind=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var10 string
				templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(signals.Signal("rangeStart"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 213, Col: 45}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if args.Required {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " required")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "> <input type=\"hidden\" name=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 string
				templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(args.Name + "_end")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 220, Col: 30}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" data-bind=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var12 string
				templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(signals.Signal("rangeEnd"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 221, Col: 43}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<!-- Single mode: single hidden input --> <input type=\"hidden\" name=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var13 string
				templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(args.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 227, Col: 21}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\" data-bind=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var14 string
				templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(signals.Signal("selectedDate"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 228, Col: 47}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if args.Required {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, " required")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, ">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "<!-- Input field with calendar icon -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if args.Mode == "range" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<!-- Range mode: use DateInput with calendar icon outside --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}

			// Initial values for range mode
			initialStartValue := ""
			initialEndValue := ""

			// Parse the initial range input value
			if initialInputValue != "" {
				parts := strings.Split(initialInputValue, " - ")
				if len(parts) == 2 {
					initialStartValue = parts[0]
					initialEndValue = parts[1]
				} else if len(parts) == 1 {
					initialStartValue = parts[0]
				}
			}

			// DateInput will handle calendar coordination directly via CalendarID
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "<div class=\"relative flex items-center gap-2\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if args.OpenOnFocus || !args.DisablePopoverOpenOnFocus {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, " data-on-focus__capture=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var15 string
				templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs("evt.target.tagName.toLowerCase() === 'input' ? " + signals.Set("open", "true") + " : null")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 259, Col: 121}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "><!-- DateInput without postfix --><div class=\"flex-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = dateinput.DateInput(dateinput.DateInputArgs{
				ID:         dateInputID,
				Name:       "", // No form submission for DateInput itself
				Mode:       "range",
				StartValue: initialStartValue,
				EndValue:   initialEndValue,
				StartName:  "",           // Handled by DatePicker's hidden inputs
				EndName:    "",           // Handled by DatePicker's hidden inputs
				CalendarID: datePickerID, // Coordinate with calendar using same namespace
				Disabled:   args.Disabled,
				Required:   args.Required,
				Class:      args.InputClass,
				Attributes: map[string]any{
					"data-on-keydown": "evt.key === 'Escape' ? " + signals.Set("open", "false") + " : null",
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "</div><!-- Calendar icon positioned outside --><div class=\"flex-shrink-0\"><button type=\"button\" class=\"text-muted-foreground hover:text-foreground\" tabindex=\"-1\" data-on-click=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(calendarIconClickHandler)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 287, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "\"><svg class=\"h-4 w-4\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 2v4\"></path> <path d=\"M16 2v4\"></path> <rect width=\"18\" height=\"18\" x=\"3\" y=\"4\" rx=\"2\"></rect> <path d=\"M3 10h18\"></path></svg></button></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "<!-- Single mode: use DateInput with proper signal synchronization --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}

			// DateInput will handle calendar coordination directly via CalendarID
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "<div")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if args.OpenOnFocus || !args.DisablePopoverOpenOnFocus {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, " data-on-focus__capture=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var17 string
				templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs("evt.target.tagName.toLowerCase() === 'input' ? " + signals.Set("open", "true") + " : null")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 316, Col: 121}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = dateinput.DateInput(dateinput.DateInputArgs{
				ID:          dateInputID,
				Name:        "", // No form submission for DateInput itself
				Placeholder: placeholder,
				Value:       initialInputValue,
				CalendarID:  datePickerID, // Coordinate with calendar using same namespace
				Disabled:    args.Disabled,
				Required:    args.Required,
				Class:       args.InputClass,
				Attributes: map[string]any{
					"data-on-keydown": "evt.key === 'Escape' ? " + signals.Set("open", "false") + " : null",
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "<!-- Calendar icon button positioned separately to maintain signal scope --><button type=\"button\" class=\"absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground\" tabindex=\"-1\" data-on-click=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var18 string
			templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(calendarIconClickHandler)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 337, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "\"><svg class=\"h-4 w-4\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 2v4\"></path> <path d=\"M16 2v4\"></path> <rect width=\"18\" height=\"18\" x=\"3\" y=\"4\" rx=\"2\"></rect> <path d=\"M3 10h18\"></path></svg></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "<!-- Calendar popover -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = DatePickerPopover(DatePickerPopoverProps{
			ID:                  datePickerID,
			DateInputID:         dateInputID,
			Mode:                args.Mode,
			NumberOfMonths:      args.NumberOfMonths,
			MinDate:             args.MinDate,
			MaxDate:             args.MaxDate,
			DisabledDates:       args.DisabledDates,
			HideOutsideDays:     args.HideOutsideDays,
			CloseOnSelect:       closeOnSelect,
			Class:               args.CalendarClass,
			Position:            args.PopoverPosition,
			InitialSelectedDate: initialSelectedDate,
			InitialDisplayMonth: initialDisplayMonth,
			InitialRangeStart:   initialRangeStart,
			InitialRangeEnd:     initialRangeEnd,
			DatePickerInputsID:  args.DatePickerInputsID,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DatePickerPopover renders the calendar popover with keyboard navigation
func DatePickerPopover(args DatePickerPopoverProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var19 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var19 == nil {
			templ_7745c5c3_Var19 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// IMPORTANT: We need to use the same signal namespace as the parent DatePicker
		// Don't create new signals here - reference the existing ones
		signals := utils.Signals(args.ID, DatePickerSignals{})

		// Popover show/hide - explicitly handle undefined to prevent flash
		showExpr := signals.Signal("open") + " === true"

		// DatePicker open check (following select.templ pattern)
		datePickerOpenCheck := "document.querySelector('[data-datepicker-id=\"" + args.ID + "\"]') && " + signals.Signal("open")

		// Determine the correct input ID for focus
		inputID := args.DateInputID
		if args.Mode == "range" {
			inputID = args.DateInputID + "_start" // Focus on start input in range mode
		}

		// Escape: close and return focus to input
		escapeHandler := "evt.key === 'Escape' && " + datePickerOpenCheck + " ? (evt.preventDefault(), evt.stopPropagation(), " +
			signals.Set("open", "false") + ", document.getElementById('" + inputID + "').focus()) : null"

		// Tab: close but allow tab to continue
		tabHandler := "evt.key === 'Tab' && " + datePickerOpenCheck + " ? " + signals.Set("open", "false") + " : null"

		// Combine keyboard handlers
		keyHandler := escapeHandler + "; " + tabHandler

		// Convert number of months
		numMonths := args.NumberOfMonths
		if numMonths <= 0 {
			numMonths = 1
		}

		// Calendar date selection handler - update both DatePicker and DateInput signals
		dateSelectHandler := ""

		// Build the handler conditionally
		if args.Mode == "range" {
			// Range mode handler - sync with DateInput signals
			dateInputSignals := utils.Signals(args.DateInputID, dateinput.DateInputSignals{})

			dateSelectHandler = "(evt.detail.rangeStart && evt.detail.rangeEnd) ? (" +
				"(startDisplay => endDisplay => (" +
				dateInputSignals.Set("startInputValue", "startDisplay") + ", " +
				dateInputSignals.Set("startDateValue", "evt.detail.rangeStart") + ", " +
				dateInputSignals.Set("endInputValue", "endDisplay") + ", " +
				dateInputSignals.Set("endDateValue", "evt.detail.rangeEnd") + ", " +
				signals.Set("rangeStart", "evt.detail.rangeStart") + ", " +
				signals.Set("rangeEnd", "evt.detail.rangeEnd") +
				"))(evt.detail.rangeStart.replace(/-/g, '/'))(evt.detail.rangeEnd.replace(/-/g, '/'))" +
				") : evt.detail.rangeStart ? (" +
				"(startDisplay => (" +
				dateInputSignals.Set("startInputValue", "startDisplay") + ", " +
				dateInputSignals.Set("startDateValue", "evt.detail.rangeStart") + ", " +
				dateInputSignals.Set("endInputValue", "''") + ", " +
				dateInputSignals.Set("endDateValue", "''") + ", " +
				signals.Set("rangeStart", "evt.detail.rangeStart") + ", " +
				signals.Set("rangeEnd", "''") +
				"))(evt.detail.rangeStart.replace(/-/g, '/'))" +
				") : null"

			// Add close logic if needed for range mode
			if args.CloseOnSelect {
				dateSelectHandler = "(" + dateSelectHandler + ", " + signals.Set("open", "false") + ")"
			}
		} else {
			// Single date mode handler - update both DateInput and DatePicker signals
			dateInputSignals := utils.Signals(args.DateInputID, dateinput.DateInputSignals{})
			dateSelectHandler = "evt.detail.selectedDate ? (" +
				"(displayDate => (" +
				dateInputSignals.Set("inputValue", "displayDate") + ", " +
				dateInputSignals.Set("dateValue", "evt.detail.selectedDate") + ", " +
				signals.Set("selectedDate", "evt.detail.selectedDate") +
				"))(evt.detail.selectedDate.replace(/-/g, '/'))" +
				") : null"

			// Add close logic if needed for single mode
			if args.CloseOnSelect {
				dateSelectHandler = "(" + dateSelectHandler + ", " + signals.Set("open", "false") + ")"
			}
		}

		// Month navigation handler - sync display month
		monthChangeHandler := "evt.detail.displayMonth ? " + signals.Set("displayMonth", "evt.detail.displayMonth") + " : null"

		// Position classes
		positionClasses := "absolute left-0 z-50 p-0"
		if args.Position == "top" {
			positionClasses += " bottom-full mb-1"
		} else {
			positionClasses += " top-full mt-1"
		}
		var templ_7745c5c3_Var20 = []any{positionClasses}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var20...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "<div data-slot=\"datepicker-popover\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var21 string
		templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var20).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "\" data-show=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var22 string
		templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(showExpr)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 479, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "\" data-on-keydown__window=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var23 string
		templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(keyHandler)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 480, Col: 38}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "\" style=\"width: max-content; display: none;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var24 = []any{"rounded-md border bg-popover p-4 text-popover-foreground shadow-md " + args.Class}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var24...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var25 string
		templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var24).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/datepicker/datepicker.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = calendar.Calendar(calendar.CalendarProps{
			ID:                 args.ID,
			Mode:               args.Mode,
			SelectedDate:       args.InitialSelectedDate,
			DefaultDate:        args.InitialDisplayMonth,
			RangeStart:         args.InitialRangeStart,
			RangeEnd:           args.InitialRangeEnd,
			NumberOfMonths:     numMonths,
			Disabled:           args.DisabledDates,
			HideOutsideDays:    args.HideOutsideDays,
			DatePickerInputsID: args.DatePickerInputsID, // Pass DatePickerInputsID for signal coordination
			MinDate:            args.MinDate,
			MaxDate:            args.MaxDate,
			Attributes: map[string]any{
				"data-on-date-select":  dateSelectHandler,
				"data-on-month-change": monthChangeHandler,
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
