// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package calendar

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"crypto/rand"
	"fmt"
	"github.com/coreycole/datastarui/utils"
	"time"
)

// CalendarDayData represents pre-calculated day information
type CalendarDayData struct {
	DateString     string // YYYY-MM-DD format
	DayNumber      int    // Day of month (1-31)
	IsCurrentMonth bool   // Is this day in the target month
	IsToday        bool   // Is this today's date
	IsOutsideDay   bool   // Is this day outside the target month
}

// calculateDayData pre-calculates day information based on the current month
func calculateDayData(dayIndex, monthOffset int, currentDateStr, todaySignal string) CalendarDayData {
	// Parse the current date to determine the year and month being displayed
	currentDate, err := time.Parse("2006-01-02", currentDateStr)
	if err != nil {
		// Fallback to current month if parsing fails
		currentDate = time.Now()
	}

	// Add month offset for multi-month calendars
	targetDate := currentDate.AddDate(0, monthOffset, 0)
	year := targetDate.Year()
	month := int(targetDate.Month())

	// Calculate the first day of the month and its weekday
	firstDay := time.Date(year, time.Month(month), 1, 0, 0, 0, 0, time.UTC)
	startWeekday := int(firstDay.Weekday()) // Sunday = 0

	// Calculate the actual day number for this grid position
	dayNumber := dayIndex - startWeekday + 1

	// Determine if this is in the current month or outside days
	isCurrentMonth := dayNumber >= 1 && dayNumber <= daysInMonth(year, month)

	// Calculate the actual date for this cell
	var actualDate time.Time
	var displayDayNumber int

	if dayNumber <= 0 {
		// Previous month
		prevMonth := firstDay.AddDate(0, -1, 0)
		prevMonthDays := daysInMonth(prevMonth.Year(), int(prevMonth.Month()))
		displayDayNumber = prevMonthDays + dayNumber
		actualDate = time.Date(prevMonth.Year(), prevMonth.Month(), displayDayNumber, 0, 0, 0, 0, time.UTC)
	} else if dayNumber > daysInMonth(year, month) {
		// Next month
		nextMonth := firstDay.AddDate(0, 1, 0)
		displayDayNumber = dayNumber - daysInMonth(year, month)
		actualDate = time.Date(nextMonth.Year(), nextMonth.Month(), displayDayNumber, 0, 0, 0, 0, time.UTC)
	} else {
		// Current month
		displayDayNumber = dayNumber
		actualDate = time.Date(year, time.Month(month), dayNumber, 0, 0, 0, 0, time.UTC)
	}

	// Format date string
	dateString := actualDate.Format("2006-01-02")

	// Check if this is today
	today := time.Now().Format("2006-01-02")
	isToday := dateString == today

	return CalendarDayData{
		DateString:     dateString,
		DayNumber:      displayDayNumber,
		IsCurrentMonth: isCurrentMonth,
		IsToday:        isToday,
		IsOutsideDay:   !isCurrentMonth,
	}
}

// Helper function to get days in a month
func daysInMonth(year, month int) int {
	return time.Date(year, time.Month(month+1), 0, 0, 0, 0, 0, time.UTC).Day()
}

// CalendarSignals defines the signal structure for calendar components
type CalendarSignals struct {
	CurrentDate  string `json:"currentDate"`
	Mode         string `json:"mode"`
	Today        string `json:"today"`
	SelectedDate string `json:"selectedDate"`
	RangeStart   string `json:"rangeStart"`
	RangeEnd     string `json:"rangeEnd"`
}

// Calendar renders a simple, elegant calendar
func Calendar(args CalendarProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// Generate unique ID
		calendarID := args.ID
		if calendarID == "" {
			b := make([]byte, 4)
			rand.Read(b)
			calendarID = fmt.Sprintf("calendar_%x", b)
		}

		// Set defaults
		mode := args.Mode
		if mode == "" {
			mode = "single"
		}

		numberOfMonths := args.NumberOfMonths
		if numberOfMonths <= 0 {
			numberOfMonths = 1
		}

		// Determine the initial month to display
		var currentDateStr string
		now := time.Now()
		if args.DefaultDate != "" {
			// Use the provided DefaultDate, normalized to first day of month
			if t, err := time.Parse("2006-01-02", args.DefaultDate); err == nil {
				currentDateStr = fmt.Sprintf("%04d-%02d-01", t.Year(), int(t.Month()))
			} else {
				// Fallback to current month if DefaultDate is invalid
				currentDateStr = fmt.Sprintf("%04d-%02d-01", now.Year(), int(now.Month()))
			}
		} else {
			// Default to current month
			currentDateStr = fmt.Sprintf("%04d-%02d-01", now.Year(), int(now.Month()))
		}

		// Today string for highlighting
		todayStr := now.Format("2006-01-02")

		// Create signals using the structured system
		signals := utils.Signals(calendarID, CalendarSignals{
			CurrentDate:  currentDateStr,
			Mode:         mode,
			Today:        todayStr,
			SelectedDate: args.SelectedDate,
			RangeStart:   args.RangeStart,
			RangeEnd:     args.RangeEnd,
		})

		classes := calendarVariants(args.Class)
		var templ_7745c5c3_Var2 = []any{"p-3 " + classes}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if args.DatePickerInputsID == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " data-signals=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(signals.DataSignals)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 151, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, args.Attributes)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CalendarHeader(CalendarHeaderProps{ID: calendarID, NumberOfMonths: numberOfMonths}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- Months container with responsive flex layout -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if numberOfMonths == 1 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<!-- Single month layout --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = CalendarGrid(CalendarGridProps{
				ID:                 calendarID,
				MonthOffset:        0,
				HideOutsideDays:    args.HideOutsideDays,
				NumberOfMonths:     numberOfMonths,
				CurrentDateStr:     currentDateStr,
				Mode:               mode,
				DatePickerInputsID: args.DatePickerInputsID,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<!-- Multi-month layout - each month looks like a single calendar --> <div class=\"flex flex-col sm:flex-row gap-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for monthIndex := 0; monthIndex < numberOfMonths; monthIndex++ {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"flex-1\"><!-- Individual month header --><div class=\"flex justify-center pt-1 relative items-center w-full mb-4\"><div class=\"text-sm font-medium\"><span data-text=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("new Date(Date.UTC(new Date(" + signals.Signal("currentDate") + " + 'T12:00:00Z').getUTCFullYear(), new Date(" + signals.Signal("currentDate") + " + 'T12:00:00Z').getUTCMonth() + " + fmt.Sprintf("%d", monthIndex) + ", 1, 12, 0, 0)).toLocaleString('default', { month: 'long', year: 'numeric', timeZone: 'UTC' })")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 176, Col: 337}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"></span></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = CalendarGrid(CalendarGridProps{
					ID:                 calendarID,
					MonthOffset:        monthIndex,
					HideOutsideDays:    args.HideOutsideDays,
					NumberOfMonths:     numberOfMonths,
					CurrentDateStr:     currentDateStr,
					Mode:               mode,
					DatePickerInputsID: args.DatePickerInputsID,
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// CalendarHeader renders the month navigation
func CalendarHeader(args CalendarHeaderProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// Use the same signal namespace as the parent calendar - don't create new signals
		signals := utils.Signals(args.ID, CalendarSignals{})

		// Signal references
		currentDateRef := signals.Signal("currentDate")

		// Navigation expressions - simplified UTC approach
		prevMonthExpr := signals.Set("currentDate", "new Date(Date.UTC(new Date("+currentDateRef+").getUTCFullYear(), new Date("+currentDateRef+").getUTCMonth() - 1, 1)).toISOString().slice(0, 10)")
		nextMonthExpr := signals.Set("currentDate", "new Date(Date.UTC(new Date("+currentDateRef+").getUTCFullYear(), new Date("+currentDateRef+").getUTCMonth() + 1, 1)).toISOString().slice(0, 10)")

		// Month display expressions for multiple months
		numberOfMonths := args.NumberOfMonths
		if numberOfMonths <= 0 {
			numberOfMonths = 1
		}
		if numberOfMonths == 1 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<!-- Single month header --> <div class=\"flex justify-center pt-1 relative items-center w-full mb-4\"><!-- Previous month button --><button type=\"button\" class=\"inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-transparent hover:bg-accent hover:text-accent-foreground size-7 p-0 opacity-50 hover:opacity-100 absolute left-1\" data-on-click=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(prevMonthExpr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 221, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"size-4\"><path d=\"m15 18-6-6 6-6\"></path></svg></button><!-- Month/Year display --><div class=\"text-sm font-medium\"><span data-text=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs("new Date(" + currentDateRef + " + 'T12:00:00Z').toLocaleString('default', { month: 'long', year: 'numeric', timeZone: 'UTC' })")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 229, Col: 150}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\"></span></div><!-- Next month button --><button type=\"button\" class=\"inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-transparent hover:bg-accent hover:text-accent-foreground size-7 p-0 opacity-50 hover:opacity-100 absolute right-1\" data-on-click=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(nextMonthExpr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 235, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"size-4\"><path d=\"m9 18 6-6-6-6\"></path></svg></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<!-- Multi-month header with navigation --> <div class=\"flex justify-between items-center w-full mb-4\"><!-- Previous month button --><button type=\"button\" class=\"inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-transparent hover:bg-accent hover:text-accent-foreground size-7 p-0 opacity-50 hover:opacity-100\" data-on-click=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(prevMonthExpr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 249, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"size-4\"><path d=\"m15 18-6-6 6-6\"></path></svg></button><!-- Month range display --><div class=\"flex items-center space-x-1 text-sm font-medium\"><span data-text=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs("new Date(" + currentDateRef + " + 'T12:00:00Z').toLocaleString('default', { month: 'long', year: 'numeric', timeZone: 'UTC' })")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 257, Col: 150}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\"></span> <span>-</span> <span data-text=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs("new Date(new Date(" + currentDateRef + " + 'T12:00:00Z').getFullYear(), new Date(" + currentDateRef + " + 'T12:00:00Z').getMonth() + " + fmt.Sprintf("%d", numberOfMonths-1) + ", 1).toLocaleString('default', { month: 'long', year: 'numeric', timeZone: 'UTC' })")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 259, Col: 283}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\"></span></div><!-- Next month button --><button type=\"button\" class=\"inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-transparent hover:bg-accent hover:text-accent-foreground size-7 p-0 opacity-50 hover:opacity-100\" data-on-click=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(nextMonthExpr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 265, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"size-4\"><path d=\"m9 18 6-6-6-6\"></path></svg></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// CalendarGrid renders the calendar days
func CalendarGrid(args CalendarGridProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var14 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var14 == nil {
			templ_7745c5c3_Var14 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// Use 5 weeks (35 days) for all calendars for a cleaner, more consistent look
		weeksNeeded := 5
		totalDays := weeksNeeded * 7
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "<div class=\"w-full border-collapse\"><!-- Day headers --><div class=\"grid grid-cols-7 gap-1 mb-2\"><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">Su</div><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">Mo</div><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">Tu</div><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">We</div><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">Th</div><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">Fr</div><div class=\"text-muted-foreground rounded-md size-8 font-normal text-[0.8rem] flex items-center justify-center p-0\">Sa</div></div><!-- Calendar days grid --><div class=\"grid grid-cols-7 gap-1\"><!-- Generate 35 days (5 weeks × 7 days) for cleaner layout -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for dayIndex := 0; dayIndex < totalDays; dayIndex++ {
			templ_7745c5c3_Err = CalendarDay(CalendarDayProps{
				ID:                 args.ID,
				DayIndex:           dayIndex,
				MonthOffset:        args.MonthOffset,
				HideOutsideDays:    args.HideOutsideDays,
				CurrentDateStr:     args.CurrentDateStr,
				Mode:               args.Mode,
				DatePickerInputsID: args.DatePickerInputsID,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// CalendarDay renders individual day button with pre-calculated data
func CalendarDay(args CalendarDayProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var15 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var15 == nil {
			templ_7745c5c3_Var15 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// Share the same signal namespace as the parent calendar - don't create new signals
		signals := utils.Signals(args.ID, CalendarSignals{})

		// Pre-calculate day data using the static current date for now
		// The real fix is that we need to make the grid responsive to currentDate signal changes
		// For now, let's calculate the day correctly based on the fallback
		currentDateForCalc := args.CurrentDateStr
		if currentDateForCalc == "" {
			// Fallback
			now := time.Now()
			currentDateForCalc = fmt.Sprintf("%04d-%02d-01", now.Year(), now.Month())
		}

		dayData := calculateDayData(args.DayIndex, args.MonthOffset, currentDateForCalc, signals.Signal("today"))

		// Create calendar day handler using expression builder
		dayHandler := newCalendarDayHandler(args.ID, signals, args.MonthOffset, args.Mode, dayData.DayNumber)

		var clickHandler string
		// Only allow clicks on days in the current month
		if !dayData.IsCurrentMonth {
			clickHandler = utils.NewExpression().
				Statement("evt.preventDefault()").
				Statement("evt.stopPropagation()").
				Build()
		} else {
			// Use expression builder for clean click handling
			clickHandler = dayHandler.buildClickHandler()

			// Add DateInput signal coordination if needed
			if args.DatePickerInputsID != "" {
				dateInputSync := dayHandler.buildDateInputSync(args.DatePickerInputsID)
				clickHandler += "; " + dateInputSync
			}
		}

		// CSS classes
		baseClasses := "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 size-8 p-0 font-normal aria-selected:opacity-100 cursor-pointer hover:bg-accent hover:text-accent-foreground"

		// Add styling for outside days
		if dayData.IsOutsideDay {
			baseClasses += " text-muted-foreground opacity-50"
		}

		// Add today styling
		todayClasses := ""
		if dayData.IsToday {
			todayClasses = " bg-accent text-accent-foreground font-semibold"
		}

		// Use expression builder for clean conditional classes
		var selectionClasses string
		if dayData.IsCurrentMonth {
			// Create calendar selection class helper
			selectionClassHelper := newCalendarSelectionClasses(args.ID, signals, args.MonthOffset, dayData.DayNumber, args.Mode)
			selectionClasses = selectionClassHelper.build()
		} else {
			// For outside days, no selection styling
			selectionClasses = "{}"
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "<div class=\"relative p-0 text-center text-sm focus-within:relative focus-within:z-20 flex items-center justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 = []any{baseClasses + todayClasses}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var16...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "<button type=\"button\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var16).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "\" data-class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 string
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(selectionClasses)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 379, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "\" data-on-click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 string
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(clickHandler)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 380, Col: 31}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var20 string
		templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", dayData.DayNumber))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/calendar/calendar.templ`, Line: 382, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
